artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts_root
  source_url: https://github.com/sidhyaashu/Project_data/raw/master/archive.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion